trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/**
      - public/**
      - package.json
      - package-lock.json
      - pipelines/ui-pipeline.yml

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: "20.x"
  AZURE_SERVICE_CONNECTION: "moath-sp-new"

stages:
# ============================
# BUILD
# ============================
- stage: Build
  displayName: "Build UI"
  jobs:
  - job: BuildUI
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: "Use Node $(NODE_VERSION)"

    # ✅ BUILD FROM REPO ROOT
    - script: |
        set -e
        npm ci
        npm run build
      displayName: "Install & Build UI"

    # ✅ ARCHIVE ROOT build/
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: "build"
        includeRootFolder: false
        archiveType: zip
        archiveFile: "$(Build.ArtifactStagingDirectory)/ui.zip"
        replaceExistingArchive: true
      displayName: "Archive build output"

    - publish: "$(Build.ArtifactStagingDirectory)/ui.zip"
      artifact: drop
      displayName: "Publish artifact"

# ============================
# DEV
# ============================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  variables:
    APP_SERVICE_NAME: "ui-moath-dev"
    REACT_APP_API_BASE_URL: "https://apim-moath-dev-v2.azure-api.net"
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Deploy UI to DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              appName: $(APP_SERVICE_NAME)
              package: "$(Pipeline.Workspace)/drop/ui.zip"

          # ✅ FINAL FIX — AZURE CLI (DEV)
          - task: AzureCLI@2
            displayName: "Set DEV Node 20 runtime + startup"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-dev \
                  --linux-fx-version "NODE|20-lts"

                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-dev \
                  --startup-file "npx serve -s . --listen 8080"

                az webapp config appsettings set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-dev \
                  --settings \
                    WEBSITES_PORT=8080 \
                    NODE_ENV=production \
                    CI=false \
                    REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL)

# ============================
# QA
# ============================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  variables:
    APP_SERVICE_NAME: "ui-moath-qa"
    REACT_APP_API_BASE_URL: "https://apim-moath-qa-v2.azure-api.net"
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Deploy UI to QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              appName: $(APP_SERVICE_NAME)
              package: "$(Pipeline.Workspace)/drop/ui.zip"

          # ✅ FINAL FIX — AZURE CLI (QA)
          - task: AzureCLI@2
            displayName: "Set QA Node 20 runtime + startup"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-qa \
                  --linux-fx-version "NODE|20-lts"

                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-qa \
                  --startup-file "npx serve -s . --listen 8080"

                az webapp config appsettings set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-qa \
                  --settings \
                    WEBSITES_PORT=8080 \
                    NODE_ENV=production \
                    CI=false \
                    REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL)

# ============================
# PROD
# ============================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  variables:
    APP_SERVICE_NAME: "ui-moath-prod"
    REACT_APP_API_BASE_URL: "https://apim-moath-prod-v2.azure-api.net"
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Deploy UI to PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              appName: $(APP_SERVICE_NAME)
              package: "$(Pipeline.Workspace)/drop/ui.zip"

          # ✅ FINAL FIX — AZURE CLI (PROD)
          - task: AzureCLI@2
            displayName: "Set PROD Node 20 runtime + startup"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-prod \
                  --linux-fx-version "NODE|20-lts"

                az webapp config set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-prod \
                  --startup-file "npx serve -s . --listen 8080"

                az webapp config appsettings set \
                  --name $(APP_SERVICE_NAME) \
                  --resource-group rg-moath-prod \
                  --settings \
                    WEBSITES_PORT=8080 \
                    NODE_ENV=production \
                    CI=false \
                    REACT_APP_API_BASE_URL=$(REACT_APP_API_BASE_URL)
