trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: "20.x"
  AZURE_SERVICE_CONNECTION: "moath-sp-new"

stages:

# =====================================================
# DEV
# =====================================================
- stage: Dev
  displayName: Deploy DEV
  jobs:
  - job: Dev
    displayName: Build & Deploy DEV
    variables:
      APP_SERVICE_NAME: ui-moath-dev
      REACT_APP_API_BASE_URL: https://apim-moath-dev-v2.azure-api.net
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)

    - script: |
        npm ci
        npm run build
      displayName: Build UI (DEV)
      env:
        REACT_APP_API_BASE_URL: $(REACT_APP_API_BASE_URL)

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        appName: $(APP_SERVICE_NAME)
        package: build

    - task: AzureCLI@2
      displayName: Configure DEV App Service
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-dev \
            --linux-fx-version "NODE|20-lts"

          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-dev \
            --startup-file "npx serve -s . --listen 8080"

          az webapp config appsettings set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-dev \
            --settings WEBSITES_PORT=8080 NODE_ENV=production CI=false

# =====================================================
# QA
# =====================================================
- stage: QA
  displayName: Deploy QA
  dependsOn: Dev
  jobs:
  - job: QA
    displayName: Build & Deploy QA
    variables:
      APP_SERVICE_NAME: ui-moath-qa
      REACT_APP_API_BASE_URL: https://apim-moath-qa-v2.azure-api.net
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)

    - script: |
        npm ci
        npm run build
      displayName: Build UI (QA)
      env:
        REACT_APP_API_BASE_URL: $(REACT_APP_API_BASE_URL)

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        appName: $(APP_SERVICE_NAME)
        package: build

    - task: AzureCLI@2
      displayName: Configure QA App Service
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-qa \
            --linux-fx-version "NODE|20-lts"

          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-qa \
            --startup-file "npx serve -s . --listen 8080"

          az webapp config appsettings set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-qa \
            --settings WEBSITES_PORT=8080 NODE_ENV=production CI=false

# =====================================================
# PROD
# =====================================================
- stage: Prod
  displayName: Deploy PROD
  dependsOn: QA
  jobs:
  - job: Prod
    displayName: Build & Deploy PROD
    variables:
      APP_SERVICE_NAME: ui-moath-prod
      REACT_APP_API_BASE_URL: https://apim-moath-prod-v2.azure-api.net
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)

    - script: |
        npm ci
        npm run build
      displayName: Build UI (PROD)
      env:
        REACT_APP_API_BASE_URL: $(REACT_APP_API_BASE_URL)

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        appName: $(APP_SERVICE_NAME)
        package: build

    - task: AzureCLI@2
      displayName: Configure PROD App Service
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-prod \
            --linux-fx-version "NODE|20-lts"

          az webapp config set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-prod \
            --startup-file "npx serve -s . --listen 8080"

          az webapp config appsettings set \
            --name $(APP_SERVICE_NAME) \
            --resource-group rg-moath-prod \
            --settings WEBSITES_PORT=8080 NODE_ENV=production CI=false
